<template>
  <div>
    <table>
      <thead>
        <tr>
          <th>1</th>
          <th>2</th>
          <th>3</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Hola!</td>
          <td>Hola!</td>
          <td>Hola!</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
<script></script>
